config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  def parse_ingredients
    list = ingredients.split(";")
    
    list.map! do |i|
      if i.include?(".")
        l = i.split(".")

        [l.first, l.last]
      else
        [i]
      end
    end

    list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
    
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  def show
  end

  def new
  end

  def create
    p "tried to create"
    Blog.new(blog_params).save!

    redirect_to blogs_path
  end

  private

  def blog_params
    {title: params[:title], body: params[:body]}
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    render locals: {recipes: Recipe.all}
  end

  def show
    render locals: {recipe: Recipe.find(params[:id])}
  end

  def new
    render locals: {recipe: Recipe.new}
  end

  def create
    recipe = Recipe.new(recipe_params)

    if recipe.save
      redirect_to recipes_path
    else
      render :new, locals: {recipe: recipe}
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :ingredients, :instructions)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/_blog.haml
= blog.title
= blog.body

app/views/blogs/index.haml
.text-3xl.text-center.py-3.font-semibold Ponders, Thots, and Musings

= render @blogs

app/views/blogs/new.haml
.w-full.max-w-xs
  %form.bg-white.shadow-md.rounded.px-8.pt-6.pb-8.mb-4
    = form_with model: @blog, url: blogs_path do |f|
      .mb-4
        %label.block.text-gray-700.text-sm.font-bold.mb-2 Title
        .shadow.appearance-none.border.rounded.w-full.py-2.px-3.text-gray-700.leading-tight.focus:outline-none.focus:shadow-outline
          = f.text_field :title, required: true

      .mb-6
        %label.block.text-gray-700.text-sm.font-bold.mb-2 Body
        .shadow.appearance-none.border.rounded.w-full.py-2.px-3.text-gray-700.leading-tight.focus:outline-none.focus:shadow-outline
          = f.text_area :body, required: true

      .flex.items-center.justify-between
        .bg-blue-500.hover:bg-blue-700.text-white.font-bold.py-2.px-4.rounded.focus:outline-none.focus:shadow-outline
          = f.submit "Post"

app/views/layouts/_header.haml
%header
  .flex.items-center.bg-teal-500.p-6
    .title.text-5xl= link_to "fRaMeLeSs", root_path

    .font-kong.ml-4.px-3.py-2.text-white
      = link_to "Blog", blogs_path

    .font-kong.ml-4.px-3.py-2.text-white
      = link_to "Recipes", recipes_path

app/views/layouts/application.haml
!!!
%html
  %head

    %link{href: "https://fonts.gstatic.com", rel: "preconnect"}
    %link{href: "https://fonts.googleapis.com/css2?family=Karla:wght@200;300&display=swap", rel: "stylesheet"}

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"

    = javascript_pack_tag "cursor"

    = auto_discovery_link_tag :rss, blogs_url(:format => :rss)

  %body
    .cursor

    = render 'layouts/header'

    = yield

app/views/recipes/index.haml
.max-w-2xl.mx-auto.my-4.rounded-lg.shadow.bg-lighter-green
  .flex.justify-end
    = link_to "New Recipe", new_recipe_path, class: "my-2 mr-3 bg-white bg-lighter-blue focus:shadow-outline focus:outline-none text-gray-800 hober:text-gray-900 font-semibold py-2 px-4 shadow rounded cursor-pointer transition-all duration-150 ease-linear"

  .max-w-2xl.mx-auto.bg-white.rounded-b-lg.shadow.py-4
    - recipes.each do |r|
      = link_to recipe_path(r), data: {turbolinks: false} do
        .hover:bg-blue-100.hover:text-blue-900.transition-all.duration-150.ease-linear
          .flex.justify-between.p-4
            .font-medium.ml-4
              = r.title

app/views/recipes/new.haml
.mx-auto.max-w-lg.bg-white.rounded.shadow.px-6.py-4.mt-4
  = form_with model: recipe, local: true do |f|
    .py-2
      = f.label :title, class: "block lowercase tracking-wide text-gray-700 text-sm font-semibold mb-2"
      = f.text_field :title, class: "appearance-none block w-full bg-gray-200 text-gray-700 border-2 border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-indigo-300"

      = f.label :ingredients, class: "block lowercase tracking-wide text-gray-700 text-sm font-semibold mb-2"
      = f.text_area :ingredients, class: "h-64 appearance-none block w-full bg-gray-200 text-gray-700 border-2 border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-indigo-300"

      = f.label :instructions, class: "block lowercase tracking-wide text-gray-700 text-sm font-semibold mb-2"
      = f.text_area :instructions, class: "h-64 appearance-none block w-full bg-gray-200 text-gray-700 border-2 border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-indigo-300"

    = f.submit "create recipe", class: "mt-2 bg-indigo-500 hover:bg-indigo-600 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded cursor-pointer w-full"

app/views/recipes/show.haml
.max-w-2xl.mx-auto.my-4.rounded-lg.shadow.text-gray-900
  .font-medium.text-xl.py-1.px-2 Ingredient list
  %hr.w-full

  - recipe.parse_ingredients.each do |i|
    .flex.justify-start
      .font-medium.mx-2= i.first
      - if i.length > 1
        .font-light= i.last

.max-w-2xl.mx-auto.my-4.rounded-lg.shadow
  = recipe.instructions